#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/nix/store/l4xr0655d73ark4dmgix8cw3ajpwvmbz-vscode-1.97.2/lib/vscode/code" "/home/brasky/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "" "$@"