#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/nix/store/3k12ll0sjc3crfb0saknajxd6j8g5aai-vscode-1.96.2/lib/vscode/code" "/home/brasky/.config/Code/User/globalStorage/github.copilot-chat/debugCommand/copilotDebugCommand.js" "vscode://github.copilot-chat" "" "$@"